const content = document.getElementById("projectContent");
const position = document.getElementById("casePosition");
const asset = "assets/case-study/ba-srt/";
const query = new URLSearchParams(location.search);
const requestedLanguage = query.get("lang");
let language = requestedLanguage === "de" || requestedLanguage === "en" ? requestedLanguage : (localStorage.getItem("portfolio-language") || "en");
const esc = (value) => String(value ?? "").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#039;");
const tr = (value) => typeof value === "object" && value !== null && !Array.isArray(value) ? (value[language] || value.en || value.de) : value;
const bi = (en, de) => ({en, de});

const uiCopies = {
  en:{skip:"Skip to project",back:"All projects",language:"Language",overview:"Project overview",previous:"Previous",next:"Next",slideNav:"Case study slides",goTo:"Go to slide",keyboard:"Use the arrow keys or swipe to change slides.",problem:"Problem",role:"My role",contribution:"Contribution",outcome:"Outcome",coming:"The detailed case study is still being prepared. The verified project information is shown here in the meantime.",return:"Return to projects",notFound:"Project not found",missingTitle:"This project does not exist.",missingText:"The link may be incomplete or the project may have moved.",viewWork:"View projects",caseLabel:"case study",observed:"Finding",changed:"Change",openImage:"View image at full size",closeImage:"Close image"},
  de:{skip:"Zum Projekt springen",back:"Alle Projekte",language:"Sprache",overview:"Projektübersicht",previous:"Zurück",next:"Weiter",slideNav:"Folien der Case Study",goTo:"Zu Folie",keyboard:"Mit den Pfeiltasten oder einer Wischgeste zwischen den Folien wechseln.",problem:"Problem",role:"Meine Rolle",contribution:"Beitrag",outcome:"Ergebnis",coming:"Die ausführliche Case Study ist noch in Arbeit. Bis dahin sind hier die verifizierten Projektinformationen zusammengefasst.",return:"Zurück zu den Projekten",notFound:"Projekt nicht gefunden",missingTitle:"Dieses Projekt existiert nicht.",missingText:"Der Link ist möglicherweise unvollständig oder das Projekt wurde verschoben.",viewWork:"Projekte ansehen",caseLabel:"Case Study",observed:"Erkenntnis",changed:"Anpassung",openImage:"Bild in Originalgrösse anzeigen",closeImage:"Bild schliessen"}
};
let ui = uiCopies[language];
let caseAbort;

function applyChrome(updateHistory=false) {
  ui = uiCopies[language];
  document.documentElement.lang = language;
  document.getElementById("skipLink").textContent = ui.skip;
  document.getElementById("backLabel").textContent = ui.back;
  document.getElementById("backLink").href = `index.html?lang=${language}#work`;
  document.querySelector(".brand-link").href = `index.html?lang=${language}`;
  document.querySelector(".language-switch").setAttribute("aria-label", ui.language);
  document.querySelectorAll("[data-language]").forEach((button) => button.setAttribute("aria-pressed", String(button.dataset.language === language)));
  if (updateHistory) {
    localStorage.setItem("portfolio-language", language);
    const url = new URL(location.href); url.searchParams.set("lang", language); history.replaceState(null,"",url);
  }
}
document.querySelectorAll("[data-language]").forEach((button) => button.addEventListener("click", async () => { language=button.dataset.language; applyChrome(true); await init(); }));
applyChrome();

const image = (file, alt, extra="") => `<figure class="case-figure ${extra}"><button class="case-image-button" type="button"><img src="${asset}${file}" data-alt-en="${esc(alt.en)}" data-alt-de="${esc(alt.de)}" alt="${esc(tr(alt))}" loading="lazy" /><span class="case-image-hint" aria-hidden="true">↗</span></button></figure>`;
const metric = (value, label) => `<div class="case-metric"><strong>${value}</strong><span>${tr(label)}</span></div>`;
const pair = (finding, decision) => `<div class="decision-pair"><div><span>${ui.observed}</span><p>${tr(finding)}</p></div><div><span>${ui.changed}</span><p>${tr(decision)}</p></div></div>`;

const slides = [
  {
    eyebrow:bi("Bachelor thesis · Medical UX","Bachelorarbeit · Medical UX"), title:bi("GUI development for a medical SRT laser","GUI-Entwicklung für einen medizinischen SRT-Laser"),
    body:bi(
      `<p class="case-lede">The aim of the bachelor thesis was to redesign and implement the user interface of an experimental SRT laser system.</p><div class="case-summary-grid"><div><span>Task</span><p>Develop an intuitive, safe, and touch-optimized interface for the clinical treatment process.</p></div><div><span>Team</span><p>The thesis was completed by Nico Tuscano and Tobias Locher in cooperation with Meridian Medical and Bern University of Applied Sciences.</p></div><div><span>Process</span><p>Analysis, requirements, Figma prototype, usability tests, implementation, and integration.</p></div><div><span>Result</span><p>A working MVP connected to the laser prototype and covering the main treatment workflow.</p></div></div>`,
      `<p class="case-lede">Ziel der Bachelorarbeit war die Neugestaltung und Implementation der Benutzeroberfläche eines experimentellen SRT-Lasersystems.</p><div class="case-summary-grid"><div><span>Aufgabe</span><p>Entwicklung eines intuitiven, sicheren und touchoptimierten Interfaces für den klinischen Behandlungsablauf.</p></div><div><span>Team</span><p>Die Arbeit wurde von Nico Tuscano und Tobias Locher in Zusammenarbeit mit Meridian Medical und der Berner Fachhochschule durchgeführt.</p></div><div><span>Vorgehen</span><p>Analyse, Anforderungen, Figma-Prototyp, Usability-Tests, Implementation und Integration.</p></div><div><span>Ergebnis</span><p>Ein funktionsfähiger MVP, der mit dem Laserprototyp verbunden wurde und den zentralen Behandlungsworkflow abbildet.</p></div></div>`),
    media:image("srt-laser-system.webp",bi("SRT laser prototype with the implemented treatment interface","SRT-Laserprototyp mit der implementierten Behandlungsoberfläche"),"case-figure-tall")
  },
  {
    eyebrow:bi("01 · Starting point","01 · Ausgangslage"), title:bi("Redesign of the existing study GUI","Redesign des bestehenden Studien-GUI"),
    body:bi(
      `<p class="case-lede">The software used in the patient study provided insight into the core functions and treatment modes, but it also contained study-specific functions that were not intended for future versions.</p><ul class="case-list"><li>The new solution had to combine treatment, imaging, system status, and patient information in one GUI.</li><li>The system is used in a dimmed clinical environment and has to support touch and mouse input.</li><li>Laser states and safety-relevant actions must be clearly visible.</li><li>The GUI had to be integrated into an existing Qt/C++ system close to the hardware.</li></ul>`,
      `<p class="case-lede">Die in der Patientenstudie eingesetzte Software bot einen Einblick in die grundlegenden Funktionen und Behandlungsmodi. Sie enthielt jedoch auch Funktionen, die spezifisch für die Studie entwickelt wurden und in zukünftigen Versionen nicht mehr vorgesehen sind.</p><ul class="case-list"><li>Behandlung, Bildgebung, Systemstatus und Patienteninformationen sollten in einem GUI zusammengeführt werden.</li><li>Das System wird in einer abgedunkelten klinischen Umgebung eingesetzt und muss Touch- sowie Mausbedienung unterstützen.</li><li>Laserzustände und sicherheitsrelevante Aktionen müssen klar erkennbar sein.</li><li>Das GUI musste in ein bestehendes, hardwarenahes Qt/C++-System integriert werden.</li></ul>`),
    media:image("legacy-gui.webp",bi("Study GUI analyzed at the beginning of the project","Zu Projektbeginn analysiertes Studien-GUI"),"case-figure-tall")
  },
  {
    eyebrow:bi("02 · Requirements","02 · Anforderungserhebung"), title:bi("Understanding the system and treatment process","System und Behandlungsablauf verstehen"),
    body:bi(
      `<p class="case-lede">Requirements were collected systematically at the beginning of the project.</p><div class="case-steps"><div><span>01</span><p>A kick-off meeting with Meridian provided an initial overview of the application area.</p></div><div><span>02</span><p>We studied the medical context, existing system, user manuals, and comparable medical GUIs.</p></div><div><span>03</span><p>Open questions were discussed in interviews and during visits to Meridian and BFH.</p></div><div><span>04</span><p>The findings were documented as use scenarios and prioritized functional requirements.</p></div></div>`,
      `<p class="case-lede">Zu Beginn des Projekts wurden die Anforderungen an das neue GUI systematisch erhoben und analysiert.</p><div class="case-steps"><div><span>01</span><p>Ein Kick-off-Meeting mit Meridian gab einen ersten Überblick über das Anwendungsgebiet.</p></div><div><span>02</span><p>Danach folgte die Einarbeitung in den medizinischen Kontext, das bestehende System, die User Manuals und vergleichbare medizinische GUIs.</p></div><div><span>03</span><p>Offene Fragen wurden in Interviews sowie bei Besuchen bei Meridian und an der BFH geklärt.</p></div><div><span>04</span><p>Die Erkenntnisse wurden in Use Scenarios und priorisierten funktionalen Anforderungen dokumentiert.</p></div></div>`),
    media:image("bfh-laser-integration.webp",bi("Laser integration work during a project visit to BFH","Arbeiten an der Laser-Integration während eines Projektbesuchs an der BFH"))
  },
  {
    eyebrow:bi("03 · Market analysis","03 · Marktanalyse"), title:bi("Comparison with other ophthalmic systems","Vergleich mit anderen ophthalmologischen Systemen"),
    body:bi(
      `<p class="case-lede">Comparable products were examined to understand typical clinical workflows and the visual presentation used by established manufacturers.</p><div class="insight-grid"><div><span>Workflow</span><p>Guidance through the clinical process and clear indication of the current step.</p></div><div><span>Imaging</span><p>Presentation of image, treatment, and status information.</p></div><div><span>Planning</span><p>Precise placement and editing of treatment patterns.</p></div><div><span>Operation</span><p>Controls suited to a safety-critical and touch-based environment.</p></div></div>`,
      `<p class="case-lede">Um das bestehende GUI gezielt verbessern zu können, wurden vergleichbare Produkte am Markt betrachtet. Dabei ging es darum, typische klinische Workflows zu verstehen und zu analysieren, wie etablierte Hersteller diese Abläufe im GUI unterstützen und visuell umsetzen.</p><div class="insight-grid"><div><span>Workflow</span><p>Führung durch den klinischen Ablauf und klare Anzeige des aktuellen Schritts.</p></div><div><span>Bildgebung</span><p>Darstellung von Bild-, Behandlungs- und Statusinformationen.</p></div><div><span>Planung</span><p>Präzises Platzieren und Bearbeiten von Treatment Patterns.</p></div><div><span>Bedienung</span><p>Bedienelemente für ein sicherheitskritisches und touchbasiertes Umfeld.</p></div></div>`),
    media:image("market-navilas.webp",bi("Navilas interface included in the market analysis","Navilas-Oberfläche aus der Marktanalyse"))
  },
  {
    eyebrow:bi("04 · Design concept","04 · Designkonzept"), title:bi("Setup, Plan, Treat, Report","Setup, Plan, Treat, Report"),
    body:bi(
      `<p class="case-lede">The treatment process was divided into four visible steps.</p><ol class="workflow-strip"><li><span>01</span><strong>Setup</strong><p>Open or create the patient record and prepare treatment parameters.</p></li><li><span>02</span><strong>Plan</strong><p>Create and position the treatment patterns.</p></li><li><span>03</span><strong>Treat</strong><p>Perform the laser treatment and display its progress.</p></li><li><span>04</span><strong>Report</strong><p>Complete the treatment and generate the report.</p></li></ol><p class="case-note">The Imaging View is available separately and provides a larger OCT display for assessing image quality.</p>`,
      `<p class="case-lede">Der Behandlungsprozess wurde in vier sichtbare Schritte gegliedert.</p><ol class="workflow-strip"><li><span>01</span><strong>Setup</strong><p>Patientenakte öffnen oder erstellen und Behandlungsparameter vorbereiten.</p></li><li><span>02</span><strong>Plan</strong><p>Treatment Patterns erstellen und positionieren.</p></li><li><span>03</span><strong>Treat</strong><p>Laserbehandlung durchführen und den Fortschritt anzeigen.</p></li><li><span>04</span><strong>Report</strong><p>Behandlung abschliessen und Report generieren.</p></li></ol><p class="case-note">Die Imaging View ist separat erreichbar und stellt den OCT-Scan grösser dar, damit die Bildqualität besser eingeschätzt werden kann.</p>`),
    media:image("prototype-final-plan.webp",bi("Final prototype of the Plan step","Finaler Prototyp des Schritts Plan"))
  },
  {
    eyebrow:bi("05 · Color palette","05 · Farbpalette"), title:bi("Dark interface with functional signal colors","Dunkles GUI mit funktionalen Signalfarben"),
    body:bi(
      `<p class="case-lede">A dark design was selected because the system is used in a dimmed clinical environment. The Meridian style guide was extended with functional colors for the user interface.</p><div class="case-summary-grid"><div><span>Dark base</span><p>Reduces bright surfaces and supports the presentation of medical images.</p></div><div><span>Blue</span><p>Primary actions and active navigation.</p></div><div><span>Green</span><p>Ready states and successful actions.</p></div><div><span>Orange and red</span><p>Warnings, errors, and safety-relevant states.</p></div></div><p class="case-note">Information is not communicated through color alone. Text, icons, and clearly differentiated states are used in addition.</p>`,
      `<p class="case-lede">Da das System in einer abgedunkelten klinischen Umgebung betrieben wird, wurde bewusst ein dunkles GUI-Design gewählt. Der bestehende Meridian Styleguide wurde für die Benutzeroberfläche funktional erweitert.</p><div class="case-summary-grid"><div><span>Dunkle Basis</span><p>Reduziert helle Flächen und unterstützt die Darstellung medizinischer Bilddaten.</p></div><div><span>Blau</span><p>Primäre Aktionen und aktive Navigation.</p></div><div><span>Grün</span><p>Bereitschaftszustände und erfolgreiche Aktionen.</p></div><div><span>Orange und Rot</span><p>Warnungen, Fehler und sicherheitsrelevante Zustände.</p></div></div><p class="case-note">Informationen werden nicht ausschliesslich über Farbe vermittelt. Zusätzlich kommen Text, Icons und klar unterscheidbare Zustände zum Einsatz.</p>`),
    media:image("color-palette.webp",bi("Color palette developed for the SRT GUI","Für das SRT-GUI entwickelte Farbpalette"),"case-figure-tall")
  },
  {
    eyebrow:bi("06 · Prototyping","06 · Prototyping"), title:bi("Development of the Figma prototype","Entwicklung des Figma-Prototyps"),
    body:bi(
      `<p class="case-lede">The design principles and requirements were translated into several Figma iterations.</p><div class="iteration-list"><div><span>First design</span><p>Initial arrangement of treatment controls, imaging, and status information.</p></div><div><span>Further development</span><p>Revision of the hierarchy and treatment workflow based on discussions with Meridian and technical findings.</p></div><div><span>Final prototype</span><p>Complete interactive workflow with realistic AMD images for the usability-test scenarios.</p></div></div>`,
      `<p class="case-lede">Die erarbeiteten Designgrundlagen und Anforderungen wurden in mehreren Figma-Iterationen in konkrete Layout- und Interaktionsentscheidungen übersetzt.</p><div class="iteration-list"><div><span>Erster Entwurf</span><p>Erste Anordnung von Behandlungssteuerung, Bildgebung und Statusinformationen.</p></div><div><span>Weiterentwicklung</span><p>Überarbeitung der Hierarchie und des Behandlungsworkflows anhand von Rückmeldungen von Meridian und technischen Erkenntnissen.</p></div><div><span>Finaler Prototyp</span><p>Vollständiger interaktiver Workflow mit realistischen AMD-Bildern für die Szenarien der Usability-Tests.</p></div></div>`),
    media:`<div class="comparison-grid">${image("prototype-first.webp",bi("First Figma design","Erster Figma-Entwurf"))}${image("prototype-second.webp",bi("Further prototype iteration","Weiterentwickelter Prototyp"))}${image("prototype-final-plan.webp",bi("Final Figma prototype","Finaler Figma-Prototyp"))}</div>`
  },
  {
    eyebrow:bi("07 · Usability tests","07 · Usability-Tests"), title:bi("Tests with specialists using the interactive prototype","Tests mit Fachpersonen am interaktiven Prototyp"),
    body:bi(
      `<p class="case-lede">After implementing Meridian’s feedback, additional feedback from specialists was collected using the interactive Figma prototype.</p><div class="metric-row">${metric("2",bi("moderated tests with physicians from the ophthalmology department at Stadtspital Triemli","betreute Tests mit Ärzten der Augenklinik des Stadtspitals Triemli"))}${metric("4",bi("additional external reviews","zusätzliche externe Rückmeldungen"))}${metric("~15",bi("ophthalmology practices contacted during recruitment","kontaktierte Augenarztpraxen bei der Rekrutierung"))}</div><p class="case-note">The tests used predefined scenarios, observation during task completion, and a structured interview. The two moderated tests with specialists were weighted more strongly in the evaluation.</p>`,
      `<p class="case-lede">Nach dem Umsetzen des Feedbacks von Meridian wurde zusätzliches Feedback von Fachpersonen am interaktiven Figma-Prototyp eingeholt.</p><div class="metric-row">${metric("2",bi("moderated tests with physicians from the ophthalmology department at Stadtspital Triemli","betreute Tests mit Ärzten der Augenklinik des Stadtspitals Triemli"))}${metric("4",bi("additional external reviews","zusätzliche externe Rückmeldungen"))}${metric("~15",bi("ophthalmology practices contacted during recruitment","kontaktierte Augenarztpraxen bei der Rekrutierung"))}</div><p class="case-note">Die Tests bestanden aus vordefinierten Szenarien, Beobachtungen während der Aufgaben und einem strukturierten Nachinterview. Die beiden betreuten Tests mit Fachpersonen wurden bei der Auswertung stärker gewichtet.</p>`),
    media:image("prototype-final-plan.webp",bi("Interactive Figma prototype used in the usability tests","Interaktiver Figma-Prototyp aus den Usability-Tests"))
  },
  {
    eyebrow:bi("08 · Findings","08 · Erkenntnisse"), title:bi("Findings were transferred directly into the implementation","Erkenntnisse wurden direkt in die Implementation übernommen"),
    body:bi(
      `<div class="decision-stack">${pair(bi("The preset function was difficult to find and buttons appeared inactive.","Die Preset-Funktion war schwierig auffindbar und Buttons wirkten teilweise deaktiviert."),bi("Place presets closer to the parameters and make interactive states clearer.","Presets näher bei den Parametern platzieren und interaktive Zustände deutlicher darstellen."))}${pair(bi("The lock/unlock mechanism for patterns was not intuitive.","Der Lock-/Unlock-Mechanismus der Patterns war nicht intuitiv."),bi("Clarify locking, reduce unnecessary pattern types, and add Undo.","Locking verständlicher gestalten, Pattern-Typen reduzieren und eine Undo-Funktion ergänzen."))}${pair(bi("The spatial relationship between OCT and SLO was unclear.","Die räumliche Orientierung zwischen OCT- und SLO-Bild war unklar."),bi("Mark the current OCT position in the SLO image.","Aktuelle OCT-Position im SLO-Bild markieren."))}${pair(bi("Overlapping points could occur when using Freehand.","Bei Freehand konnten überlappende Punkte entstehen."),bi("Improve spacing behavior and avoid duplicate points.","Abstandsverhalten verbessern und doppelte Punkte vermeiden."))}</div><p class="case-note">Since implementation had already started, the prioritized improvements were implemented directly in the GUI rather than in another Figma iteration.</p>`,
      `<div class="decision-stack">${pair(bi("The preset function was difficult to find and buttons appeared inactive.","Die Preset-Funktion war schwierig auffindbar und Buttons wirkten teilweise deaktiviert."),bi("Place presets closer to the parameters and make interactive states clearer.","Presets näher bei den Parametern platzieren und interaktive Zustände deutlicher darstellen."))}${pair(bi("The lock/unlock mechanism for patterns was not intuitive.","Der Lock-/Unlock-Mechanismus der Patterns war nicht intuitiv."),bi("Clarify locking, reduce unnecessary pattern types, and add Undo.","Locking verständlicher gestalten, Pattern-Typen reduzieren und eine Undo-Funktion ergänzen."))}${pair(bi("The spatial relationship between OCT and SLO was unclear.","Die räumliche Orientierung zwischen OCT- und SLO-Bild war unklar."),bi("Mark the current OCT position in the SLO image.","Aktuelle OCT-Position im SLO-Bild markieren."))}${pair(bi("Overlapping points could occur when using Freehand.","Bei Freehand konnten überlappende Punkte entstehen."),bi("Improve spacing behavior and avoid duplicate points.","Abstandsverhalten verbessern und doppelte Punkte vermeiden."))}</div><p class="case-note">Da zu diesem Zeitpunkt bereits mit der Implementation begonnen wurde, flossen die priorisierten Verbesserungen direkt in das implementierte GUI und nicht in eine weitere Figma-Iteration ein.</p>`),
    media:image("patterns.webp",bi("Implemented treatment patterns and states","Implementierte Treatment Patterns und Zustände"),"case-figure-square")
  },
  {
    eyebrow:bi("09 · Implementation","09 · Implementation"), title:bi("Implementation with Qt, QML, and C++","Umsetzung mit Qt, QML und C++"),
    body:bi(
      `<p class="case-lede">The new GUI was integrated into the existing system. A large part of the planned core functionality was implemented and connected to existing interfaces and application logic.</p><div class="case-summary-grid"><div><span>Treatment View</span><p>Setup, Plan, Treat, and Report as one connected process.</p></div><div><span>Laser status</span><p>Clear display of Standby, Ready, and Firing states.</p></div><div><span>Patterns</span><p>Placement, editing, locking, deletion, Freehand, Fill, and Undo.</p></div><div><span>Imaging View</span><p>Separate display for evaluating SLO and OCT images.</p></div></div>`,
      `<p class="case-lede">Das neue GUI wurde in das bestehende System integriert. Ein grosser Teil der geplanten Kernfunktionen konnte umgesetzt und mit vorhandenen Schnittstellen oder bestehender Applikationslogik verbunden werden.</p><div class="case-summary-grid"><div><span>Treatment View</span><p>Setup, Plan, Treat und Report als zusammenhängender Ablauf.</p></div><div><span>Laserstatus</span><p>Klare Darstellung der Zustände Standby, Ready und Firing.</p></div><div><span>Patterns</span><p>Platzieren, Bearbeiten, Locking, Löschen, Freehand, Fill und Undo.</p></div><div><span>Imaging View</span><p>Separate Ansicht zur Beurteilung der SLO- und OCT-Bilder.</p></div></div>`),
    media:`<div class="comparison-grid comparison-grid-two">${image("implemented-workflow.webp",bi("Implemented Plan view","Implementierte Plan-Ansicht"))}${image("implemented-treatment.webp",bi("Implemented Treat view during laser emission","Implementierte Treat-Ansicht während der Laseremission"))}</div>`
  },
  {
    eyebrow:bi("10 · Evaluation","10 · Evaluation"), title:bi("Working MVP with documented limitations","Funktionsfähiger MVP mit dokumentierten Limitationen"),
    body:bi(
      `<p class="case-lede">The final usability tests were performed on the implemented GUI. All three participants could understand the central workflows and complete the main tasks with little support.</p><div class="metric-row">${metric("3",bi("final usability tests on the implemented GUI","abschliessende Usability-Tests am implementierten GUI"))}${metric("2",bi("issues fixed directly after the tests","direkt nach den Tests behobene Probleme"))}${metric("1",bi("MVP connected to the laser prototype","mit dem Laserprototyp verbundener MVP"))}</div><ul class="case-list"><li>The guided workflow, laser status, and color coding were understood.</li><li>The Pattern Lock button and scrolling in the User Guide were corrected after the tests.</li><li>Further work is needed for pattern rotation, parameter changes, small controls, and consistent wording.</li><li>The final tests used students instead of medical end users and a 14-inch rather than 21.5-inch screen.</li></ul><blockquote>The result is a functional prototype and a basis for further development, not production-ready medical software.</blockquote>`,
      `<p class="case-lede">Die abschliessenden Usability-Tests wurden am implementierten GUI durchgeführt. Alle drei Testpersonen konnten die zentralen Abläufe nachvollziehen und die wichtigsten Aufgaben mit wenig Unterstützung durchführen.</p><div class="metric-row">${metric("3",bi("final usability tests on the implemented GUI","abschliessende Usability-Tests am implementierten GUI"))}${metric("2",bi("issues fixed directly after the tests","direkt nach den Tests behobene Probleme"))}${metric("1",bi("MVP connected to the laser prototype","mit dem Laserprototyp verbundener MVP"))}</div><ul class="case-list"><li>Der geführte Workflow, der Laserstatus und die farbliche Kennzeichnung wurden verstanden.</li><li>Der Pattern-Lock-Button und das Scrollverhalten im User Guide wurden nach den Tests korrigiert.</li><li>Verbesserungspotenzial besteht bei Pattern-Rotation, Parameteränderungen, kleinen Bedienelementen und konsistentem Wording.</li><li>Die abschliessenden Tests fanden mit Studierenden statt und auf einem 14-Zoll- statt dem vorgesehenen 21.5-Zoll-Bildschirm.</li></ul><blockquote>Das Ergebnis ist ein funktionsfähiger Prototyp und eine Grundlage für die weitere Entwicklung, jedoch noch keine produktionsreife medizinische Software.</blockquote>`),
    media:image("implemented-imaging.webp",bi("Implemented Imaging View with SLO and OCT images","Implementierte Imaging View mit SLO- und OCT-Bildern"))
  }
];

// Dense evidence is separated into focused slides so desktop presentation mode
// can remain scrollbar-free without reducing the reading size.
slides.splice(8, 1,
  {
    eyebrow:bi("08 · Findings","08 · Erkenntnisse"), title:bi("Clearer controls for treatment planning","Verständlichere Bedienung der Behandlungsplanung"),
    body:bi(
      `<p class="case-lede">The specialist feedback was translated into concrete changes for the planning workflow.</p><div class="decision-stack">${pair(bi("The preset function was difficult to find and buttons appeared inactive.","Die Preset-Funktion war schwierig auffindbar und Buttons wirkten teilweise deaktiviert."),bi("Place presets closer to the parameters and make interactive states clearer.","Presets näher bei den Parametern platzieren und interaktive Zustände deutlicher darstellen."))}${pair(bi("The lock/unlock mechanism for patterns was not intuitive.","Der Lock-/Unlock-Mechanismus der Patterns war nicht intuitiv."),bi("Clarify locking, reduce unnecessary pattern types, and add Undo.","Locking verständlicher gestalten, Pattern-Typen reduzieren und eine Undo-Funktion ergänzen."))}</div>`,
      `<p class="case-lede">Das Feedback der Fachpersonen wurde in konkrete Anpassungen der Behandlungsplanung übersetzt.</p><div class="decision-stack">${pair(bi("The preset function was difficult to find and buttons appeared inactive.","Die Preset-Funktion war schwierig auffindbar und Buttons wirkten teilweise deaktiviert."),bi("Place presets closer to the parameters and make interactive states clearer.","Presets näher bei den Parametern platzieren und interaktive Zustände deutlicher darstellen."))}${pair(bi("The lock/unlock mechanism for patterns was not intuitive.","Der Lock-/Unlock-Mechanismus der Patterns war nicht intuitiv."),bi("Clarify locking, reduce unnecessary pattern types, and add Undo.","Locking verständlicher gestalten, Pattern-Typen reduzieren und eine Undo-Funktion ergänzen."))}</div>`),
    media:image("patterns.webp",bi("Implemented treatment patterns and states","Implementierte Treatment Patterns und Zustände"),"case-figure-square")
  },
  {
    eyebrow:bi("09 · Findings","09 · Erkenntnisse"), title:bi("Better orientation in medical images","Bessere Orientierung in den medizinischen Bildern"),
    body:bi(
      `<p class="case-lede">Further findings concerned the relationship between the images and the behavior of freely drawn patterns.</p><div class="decision-stack">${pair(bi("The spatial relationship between OCT and SLO was unclear.","Die räumliche Orientierung zwischen OCT- und SLO-Bild war unklar."),bi("Mark the current OCT position in the SLO image.","Aktuelle OCT-Position im SLO-Bild markieren."))}${pair(bi("Overlapping points could occur when using Freehand.","Bei Freehand konnten überlappende Punkte entstehen."),bi("Improve spacing behavior and avoid duplicate points.","Abstandsverhalten verbessern und doppelte Punkte vermeiden."))}</div><p class="case-note">The prioritized improvements were transferred directly into the implementation.</p>`,
      `<p class="case-lede">Weitere Erkenntnisse betrafen den Zusammenhang der Bilddaten und das Verhalten frei gezeichneter Patterns.</p><div class="decision-stack">${pair(bi("The spatial relationship between OCT and SLO was unclear.","Die räumliche Orientierung zwischen OCT- und SLO-Bild war unklar."),bi("Mark the current OCT position in the SLO image.","Aktuelle OCT-Position im SLO-Bild markieren."))}${pair(bi("Overlapping points could occur when using Freehand.","Bei Freehand konnten überlappende Punkte entstehen."),bi("Improve spacing behavior and avoid duplicate points.","Abstandsverhalten verbessern und doppelte Punkte vermeiden."))}</div><p class="case-note">Die priorisierten Verbesserungen flossen direkt in die Implementation ein.</p>`),
    media:image("implemented-imaging.webp",bi("Implemented Imaging View with SLO and OCT images","Implementierte Imaging View mit SLO- und OCT-Bildern"))
  }
);

slides.splice(11, 1,
  {
    eyebrow:bi("11 · Validation","11 · Evaluation"), title:bi("The implemented workflow was understood","Der implementierte Ablauf wurde verstanden"),
    body:bi(
      `<p class="case-lede">The final usability tests were performed on the implemented GUI. All three participants understood the central workflows and completed the main tasks with little support.</p><div class="metric-row">${metric("3",bi("final usability tests on the implemented GUI","abschliessende Usability-Tests am implementierten GUI"))}${metric("2",bi("issues fixed directly after the tests","direkt nach den Tests behobene Probleme"))}${metric("1",bi("MVP connected to the laser prototype","mit dem Laserprototyp verbundener MVP"))}</div><ul class="case-list"><li>The guided workflow, laser status, and color coding were understood.</li><li>The Pattern Lock button and scrolling in the User Guide were corrected after the tests.</li></ul>`,
      `<p class="case-lede">Die abschliessenden Usability-Tests wurden am implementierten GUI durchgeführt. Alle drei Testpersonen konnten die zentralen Abläufe nachvollziehen und die wichtigsten Aufgaben mit wenig Unterstützung durchführen.</p><div class="metric-row">${metric("3",bi("final usability tests on the implemented GUI","abschliessende Usability-Tests am implementierten GUI"))}${metric("2",bi("issues fixed directly after the tests","direkt nach den Tests behobene Probleme"))}${metric("1",bi("MVP connected to the laser prototype","mit dem Laserprototyp verbundener MVP"))}</div><ul class="case-list"><li>Der geführte Workflow, der Laserstatus und die farbliche Kennzeichnung wurden verstanden.</li><li>Der Pattern-Lock-Button und das Scrollverhalten im User Guide wurden nach den Tests korrigiert.</li></ul>`),
    media:image("implemented-treatment.webp",bi("Implemented Treat view during laser emission","Implementierte Treat-Ansicht während der Laseremission"))
  },
  {
    eyebrow:bi("12 · Reflection","12 · Reflexion"), title:bi("Working MVP with documented limitations","Funktionsfähiger MVP mit dokumentierten Limitationen"),
    body:bi(
      `<p class="case-lede">The project delivered a functional prototype and a basis for further development, not production-ready medical software.</p><ul class="case-list"><li>Further work is needed for pattern rotation, parameter changes, small controls, and consistent wording.</li><li>The final tests used students instead of medical end users.</li><li>The tests ran on a 14-inch rather than the intended 21.5-inch screen.</li></ul><blockquote>The limitations are documented so that the positive test results are not interpreted beyond the test setup.</blockquote>`,
      `<p class="case-lede">Das Projekt lieferte einen funktionsfähigen Prototyp und eine Grundlage für die weitere Entwicklung, jedoch noch keine produktionsreife medizinische Software.</p><ul class="case-list"><li>Verbesserungspotenzial besteht bei Pattern-Rotation, Parameteränderungen, kleinen Bedienelementen und konsistentem Wording.</li><li>Die abschliessenden Tests fanden mit Studierenden statt und nicht mit medizinischen Endnutzenden.</li><li>Getestet wurde auf einem 14-Zoll- statt dem vorgesehenen 21.5-Zoll-Bildschirm.</li></ul><blockquote>Die Limitationen sind dokumentiert, damit die positiven Testergebnisse nicht über das Testsetting hinaus interpretiert werden.</blockquote>`),
    media:image("implemented-imaging.webp",bi("Implemented Imaging View with SLO and OCT images","Implementierte Imaging View mit SLO- und OCT-Bildern"))
  }
);

function renderPlaceholder(project) {
  position.textContent=ui.overview;
  content.innerHTML=`<article class="placeholder-case"><div class="placeholder-copy"><p class="eyebrow">${esc(tr(project.kicker))}</p><h1>${esc(tr(project.title))}</h1><p class="case-lede">${esc(tr(project.description))}</p><dl><div><dt>${ui.problem}</dt><dd>${esc(tr(project.problem))}</dd></div><div><dt>${ui.role}</dt><dd>${esc(tr(project.role))}</dd></div><div><dt>${ui.contribution}</dt><dd>${esc(tr(project.contribution))}</dd></div><div><dt>${ui.outcome}</dt><dd>${esc(tr(project.outcome))}</dd></div></dl><p class="coming-note">${ui.coming}</p><a class="btn-primary" href="index.html?lang=${language}#work">${ui.return}</a></div><figure><img src="${esc(project.image)}" alt="${esc(tr(project.imageAlt))}" /></figure></article>`;
}

function renderNotFound() {
  document.title=`${ui.notFound} · Nico Tuscano`; position.textContent=ui.notFound;
  content.innerHTML=`<section class="not-found"><p class="eyebrow">404 · ${ui.notFound}</p><h1>${ui.missingTitle}</h1><p>${ui.missingText}</p><a class="btn-primary" href="index.html?lang=${language}#work">${ui.viewWork}</a></section>`;
}

function renderCaseStudy(project) {
  caseAbort?.abort();
  caseAbort = new AbortController();
  const listenerOptions = {signal:caseAbort.signal};
  let current=Math.max(0,Math.min(slides.length-1,Number(location.hash.replace("#slide-",""))-1||0));
  content.innerHTML=`<section class="case-shell" aria-label="${esc(tr(project.title))} ${ui.caseLabel}"><p id="slideAnnouncement" class="sr-only" aria-live="polite"></p><div id="slideViewport" class="slide-viewport"><article id="caseSlide" class="case-slide" tabindex="-1"></article></div><div class="case-controls"><button id="previousSlide" class="slide-button" type="button"><span aria-hidden="true">←</span><span>${ui.previous}</span></button><nav id="slideDots" class="slide-dots" aria-label="${ui.slideNav}"></nav><button id="nextSlide" class="slide-button" type="button"><span>${ui.next}</span><span aria-hidden="true">→</span></button></div><div class="progress-track" aria-hidden="true"><span id="progressBar"></span></div><p class="keyboard-hint">${ui.keyboard}</p><dialog id="imageDialog" class="image-dialog"><div class="image-dialog-bar"><p id="imageDialogCaption"></p><button id="closeImageDialog" type="button" aria-label="${ui.closeImage}">${ui.closeImage}<span aria-hidden="true"> ×</span></button></div><div class="image-dialog-canvas"><img id="imageDialogImage" src="" alt="" /></div></dialog></section>`;
  const slide=document.getElementById("caseSlide"),dots=document.getElementById("slideDots"),previous=document.getElementById("previousSlide"),next=document.getElementById("nextSlide"),bar=document.getElementById("progressBar");
  const imageDialog=document.getElementById("imageDialog"),dialogImage=document.getElementById("imageDialogImage"),dialogCaption=document.getElementById("imageDialogCaption"),closeDialog=document.getElementById("closeImageDialog");
  dots.innerHTML=slides.map((_,i)=>`<button type="button" data-index="${i}" aria-label="${ui.goTo} ${i+1}" title="${ui.goTo} ${i+1}">${i+1}</button>`).join("");
  const update=(focus=false)=>{const item=slides[current];slide.classList.remove("slide-enter");void slide.offsetWidth;slide.classList.add("slide-enter");slide.innerHTML=`<div class="case-copy"><p class="eyebrow">${tr(item.eyebrow)}</p><h1>${tr(item.title)}</h1>${tr(item.body)}</div><div class="case-media">${item.media}</div>`;slide.querySelectorAll(".case-image-button img").forEach((img)=>{const alt=img.dataset[language==="de"?"altDe":"altEn"];img.alt=alt;img.closest("button").setAttribute("aria-label",`${ui.openImage}: ${alt}`);});position.textContent=`${String(current+1).padStart(2,"0")} / ${String(slides.length).padStart(2,"0")}`;document.getElementById("slideAnnouncement").textContent=`${tr(item.title)}, ${current+1} / ${slides.length}`;previous.disabled=current===0;next.disabled=current===slides.length-1;dots.querySelectorAll("button").forEach((dot,i)=>dot.setAttribute("aria-current",i===current?"step":"false"));bar.style.width=`${((current+1)/slides.length)*100}%`;history.replaceState(null,"",`${location.pathname}${location.search}#slide-${current+1}`);if(focus)slide.focus({preventScroll:true});};
  const go=(index,focus=true)=>{current=Math.max(0,Math.min(slides.length-1,index));update(focus);}; previous.addEventListener("click",()=>go(current-1),listenerOptions);next.addEventListener("click",()=>go(current+1),listenerOptions);dots.addEventListener("click",(event)=>{const button=event.target.closest("button[data-index]");if(button)go(Number(button.dataset.index));},listenerOptions);
  slide.addEventListener("click",(event)=>{const button=event.target.closest(".case-image-button");if(!button)return;const source=button.querySelector("img");dialogImage.src=source.currentSrc||source.src;dialogImage.alt=source.alt;dialogCaption.textContent=source.alt;imageDialog.showModal();},listenerOptions);
  closeDialog.addEventListener("click",()=>imageDialog.close(),listenerOptions);
  imageDialog.addEventListener("click",(event)=>{if(event.target===imageDialog)imageDialog.close();},listenerOptions);
  document.addEventListener("keydown",(event)=>{if(event.key==="Escape"&&imageDialog.open){event.preventDefault();imageDialog.close();return;}if(event.altKey||event.ctrlKey||event.metaKey||event.shiftKey||/^(INPUT|TEXTAREA|SELECT|BUTTON|A)$/.test(document.activeElement?.tagName))return;if(event.key==="ArrowRight"){event.preventDefault();go(current+1);}if(event.key==="ArrowLeft"){event.preventDefault();go(current-1);}},listenerOptions);
  let touchStart=null;document.getElementById("slideViewport").addEventListener("pointerdown",(event)=>{if(event.pointerType!=="mouse")touchStart={x:event.clientX,y:event.clientY};},listenerOptions);document.getElementById("slideViewport").addEventListener("pointerup",(event)=>{if(!touchStart)return;const dx=event.clientX-touchStart.x,dy=event.clientY-touchStart.y;touchStart=null;if(Math.abs(dx)>60&&Math.abs(dx)>Math.abs(dy))go(current+(dx<0?1:-1));},listenerOptions);update();
}

async function init(){try{const response=await fetch("projects.json",{cache:"no-store"});if(!response.ok)throw new Error(`HTTP ${response.status}`);const projects=await response.json(),slug=query.get("project"),project=projects.find((item)=>item.slug===slug);if(!project)return renderNotFound();document.title=`${tr(project.title)} · Nico Tuscano`;document.querySelector('meta[name="description"]').content=tr(project.description);if(project.status==="published")renderCaseStudy(project);else renderPlaceholder(project);}catch(error){console.error("Could not load project",error);renderNotFound();}}
init();
